### ISSUE TITLE
isAuthenticated() returns false after login.

### ISSUE THREAD

**Issue by thgie** [travist/flatiron-passport#2]
I used the example you provided in the README.md. But I can't get any authentication. Here is the log of req before and after login:

BEFORE: 

  secret: 'keyboard cat',
  cookies: { gs_u: '1052469230:3663:28119:1358525911905' },
  signedCookies: { 'connect.sid': '/N/ZxhdoWBbqFfCej00/tCgG' },
  sessionStore: 
   { sessions: {},
     generate: [Function],
     _events: { disconnect: [Function], connect: [Function] } },
  sessionID: 'a2Fpg3ggaa+Gb1vz5Jo9sE43',
  ended: true,
  session: 
   { cookie: 
      { path: '/',
        _expires: null,
        originalMaxAge: null,
        httpOnly: true },
     passport: {} },
  _passport: 
   { instance: 
      { _key: 'passport',
        _strategies: [Object],
        _serializers: [Object],
        _deserializers: [Object],
        _infoTransformers: [],
        _userProperty: 'user',
        version: '0.1.15',
        Passport: [Function: Passport],
        Strategy: [Function: Strategy],
        strategies: [Object] },
     session: {} },
  isAuthenticated: [Function],
  isUnauthenticated: [Function],
  logIn: [Function],
  login: [Function],
  logOut: [Function],
  logout: [Function] }

AFTER

  secret: 'keyboard cat',
  cookies: { gs_u: '1052469230:3663:28119:1358525911905' },
  signedCookies: { 'connect.sid': 'a2Fpg3ggaa+Gb1vz5Jo9sE43' },
  sessionStore: 
   { sessions: { 'a2Fpg3ggaa+Gb1vz5Jo9sE43': '{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"passport":{}}' },
     generate: [Function],
     _events: { disconnect: [Function], connect: [Function] } },
  sessionID: 'a2Fpg3ggaa+Gb1vz5Jo9sE43',
  ended: true,
  session: 
   { cookie: 
      { path: '/',
        _expires: null,
        originalMaxAge: null,
        httpOnly: true },
     passport: {} },
  _passport: 
   { instance: 
      { _key: 'passport',
        _strategies: [Object],
        _serializers: [Object],
        _deserializers: [Object],
        _infoTransformers: [],
        _userProperty: 'user',
        version: '0.1.15',
        Passport: [Function: Passport],
        Strategy: [Function: Strategy],
        strategies: [Object] },
     session: {} },
  isAuthenticated: [Function],
  isUnauthenticated: [Function],
  logIn: [Function],
  login: [Function],
  logOut: [Function],
  logout: [Function] }

Only the sessionStore object gets changed. I don't get an user object or any value out of session object. And as I said, isAuthenticated returns false after login.

**Comment by travist** [comment]
Just realized that this module needs union > 0.3.6 but my package.json indicated 0.3.4.  Try upgrading and let me know if you still have issues.  I am able to get this working on my end with Twitter.

**Comment by travist** [comment]
Should be fixed with version 0.6.  There were some issues with the LocalStrategy, but I included an example folder for you to look at.

**Comment by thgie** [comment]
Confirm works. Thanks mate!
