### ISSUE TITLE
Understanding goal of this project: doesn't Flatiron just support Connect middleware (through Union) including OAuth-clients?

### ISSUE THREAD

**Issue by geertbrit** [travist/flatiron-passport#6]
I'm very new to Flatiron and consider using it. One of the features that appeals to me is that Flatiron/union should be 100% backwards compatible with Connect. 

This would mean that Connect middleware should just run on Flatiron/Union right? Among which https://github.com/ciaranj/connect-auth and others. 

So why the need for this project? Or am I completely missing something?

**Comment by travist** [comment]
Flatiron 'supports' Connect middleware, but it does not maintain the same API.  For example.... to use middleware in Connect, you simply say 

```
var express = require('express');
var passport = require('passport');
var app = express();
// ... BOILERPLATE SETUP CODE GOES HERE ...
app.use(passport.initialize());
app.use(passport.session());
```

However, with flatiron, you cannot just simply say...

```
var flatiron = require('flatiron');
var passport = require('passport');
var app = flatiron.app;
// ... BOILERPLATE SETUP CODE GOES HERE ...
app.use(passport.initialize());
app.use(passport.session());
```

This just won't work.  It doesn't make the proper connections, so it isn't 100% portable.  Rather, you must do this to be the equivalent....

```
var flatiron = require('flatiron');
var passport = require('passport');
var app = flatiron.app;

// Initialize passport.
app.http.before.push(function(req, res) {
  passport.initialize(options)(req, res, function() {
    // Copy over the authentication methods.
    req.isAuthenticated = res.req.isAuthenticated;
    req.isUnauthenticated = res.req.isUnauthenticated;
    req.login = req.logIn = res.req.login;
    req.logout = req.logOut = res.req.logout;
    res.emit('next');
  });
});

// Initialize the session of passport.
app.http.before.push(function(req, res) {
  passport.session()(req, res, function() {
    res.emit('next');
  });
});
```

This is a lot of boilerplate code that has to be written to get Passport to work within Flatiron.  This library simply wraps that boilerplate code to make it work.  If you look at the actual code within this project, it is fairly simple and is just that... a simple wrapper.

https://github.com/travist/flatiron-passport/blob/master/flatiron-passport.js

**Comment by geertbrit** [comment]
Great knowing the differences. Thanks!

2013/2/28 Travis Tidwell notifications@github.com

**Comment by geertbrit** [comment]
Just to be clear , with your code the following IS possible?

app.use(flatpassport.initialize());
app.use(flatpassport.session());

Which would be the same as: 
app.use(flatiron.plugins.http, {
      before: [
        flatpassport.initialize(),
        flatpassport.session()
     ]
});

correct?
